name: Build Test

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  build-website:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install node
        uses: actions/setup-node@v4
        with:
          # see: https://developers.cloudflare.com/pages/configuration/build-image/#languages-and-runtime
          node-version: 18.17.1

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3
        with:
          asdf_branch: v0.15.0

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build
        run: |
          npx @cloudflare/next-on-pages@1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-on-pages-build
          # .gitignore should be included.
          # see: https://github.com/actions/upload-artifact/issues/174#issuecomment-2649189928
          path: |
            .vercel/output/static
            .gitignore
          include-hidden-files: true

  take-screenshot:
    runs-on: ubuntu-24.04
    needs: build-website
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: next-on-pages-build
          path: .

      - name: Install node
        uses: actions/setup-node@v4
        with:
          # see: https://developers.cloudflare.com/pages/configuration/build-image/#languages-and-runtime
          node-version: 18.17.1

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3
        with:
          asdf_branch: v0.15.0

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Install firefox
        run: |
          sudo add-apt-repository ppa:mozillateam/ppa
          sudo tee /etc/apt/preferences.d/mozillateamppa <<EOF
          Package: firefox*
          Pin: release o=LP-PPA-mozillateam
          Pin-Priority: 1001
          Package: firefox*
          Pin: release o=Ubuntu
          Pin-Priority: -1
          EOF
          
          sudo apt update
          sudo apt install firefox xvfb imagemagick

      - name: Run & Get screenshot
        run: |
          npx wrangler pages dev .vercel/output/static --compatibility-flag=nodejs_compat --compatibility-date=2024-11-11 &

          Xvfb :2 -screen 0 1920x1080x24 &
          export DISPLAY=:2
          sleep 10
          
          firefox http://localhost:8788 -width 1920 -height 1080 -foreground &
          sleep 30

          import -window root -crop 1920x1080+0+0 /tmp/screenshot.png

          pkill firefox
          pkill node
          pkill Xvfb

      - uses: actions/upload-artifact@v4
        name: Upload
        with:
          name: screenshot
          path: |
            /tmp/screenshot.png
