name: Docker Image CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container hashed image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

      - name: Build and push container latest image to registry
        uses: docker/build-push-action@v4
        with:
          platforms: amd64,arm64
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest
          file: ./Dockerfile
  deploy-stack:
    runs-on: ubuntu-latest
    needs: [build-website]
    steps:
      - name: Invoke deployment hook
        run: curl -X POST ${{ vars.WEBHOOK_URL }}